### ISSUE TITLE
Rust ffi crate breaks due to recent changes to core

### ISSUE THREAD

**Issue by suvamM** [microsoft/security-utilities#81]
Recent changes to `security_utilities_rust` causes build breaks in `security_utilities_rust_ffi`. This causes the downstream C# build to break as well.

To do: update `security_utility_rust_ffi` to support the new APIs in `security_utility_rust`.

**Comment by suvamM** [comment]
@jdraaijer-microsoft This is a high priority issue. Since you made the recent API changes, would you be able to make the required changes to `security_utilities_rust_ffi`?

**Comment by suvamM** [comment]
@beaubelgrave would you be able to help out with this?

**Comment by beaubelgrave** [comment]
I'll look
